from get_index_closest_cb import get_index_closest_cb
from print_list import print_list
from itertools import repeat


def update_cb_indents(cflc_indexs, cb_locations, line_data):
    """ """
    for cflc_i in cflc_indexs:
        # get closest closing brace to conditional:
        cb = get_index_closest_cb(cb_locations, cflc_i)
        # set the indent-size of line closing brace is on to indent-size of conditional:
        line_data[cb[0]][1] = line_data[cflc_i][1]
        # append the indent-size number of spaces to begining of line cotaining curly brace:
        line_data[cb[0]][2] = "".join(list(repeat(' ', line_data[cflc_i][1]))) + '}\n'
        # this curly brace has now been checked off:
        cb_locations[cb_locations.index(cb)][1] = True
    return line_data


if __name__ == "__main__":
    cflc_indexs_sorted_by_indent = \
        [
            121,
            85,
            167,
            164,
            142,
            139,
            118,
            113,
            82,
            77,
            43,
            286,
            278,
            270,
            262,
            259,
            253,
            250,
            239,
            236,
            233,
            226,
            223,
            220,
            202,
            196,
            193,
            179,
            176,
            173,
            163,
            146,
            137,
            130,
            117,
            112,
            108,
            104,
            94,
            81,
            76,
            72,
            68,
            56,
            39,
            32,
            28,
            17,
            10,
            266,
            257,
            248,
            244,
            231,
            218,
            214,
            210,
            200,
            191,
            187,
            183,
            153,
            134,
            98,
            62,
            53,
            36,
            9,
            312,
            7
        ]
    cb_locations = \
        [
            [16, False],
            [19, False],
            [31, False],
            [34, False],
            [35, False],
            [49, False],
            [50, False],
            [52, False],
            [59, False],
            [61, False],
            [71, False],
            [75, False],
            [79, False],
            [80, False],
            [88, False],
            [89, False],
            [90, False],
            [96, False],
            [97, False],
            [107, False],
            [111, False],
            [115, False],
            [116, False],
            [124, False],
            [125, False],
            [126, False],
            [132, False],
            [133, False],
            [141, False],
            [144, False],
            [145, False],
            [150, False],
            [152, False],
            [166, False],
            [169, False],
            [171, False],
            [175, False],
            [178, False],
            [181, False],
            [182, False],
            [186, False],
            [190, False],
            [195, False],
            [198, False],
            [199, False],
            [204, False],
            [209, False],
            [213, False],
            [217, False],
            [222, False],
            [225, False],
            [229, False],
            [230, False],
            [235, False],
            [238, False],
            [242, False],
            [243, False],
            [247, False],
            [252, False],
            [255, False],
            [256, False],
            [261, False],
            [264, False],
            [265, False],
            [275, False],
            [283, False],
            [291, False],
            [310, False],
            [311, False],
            [313, False]
        ]
    line_data = \
        [
            [0, 1, ' from coordType.to_xy import to_xy\n'],
            [1, 0, 'from coordType.to_rankfile import to_rankfile\n'],
            [2, 0, 'from getters.get_piece_type import get_piece_type\n'],
            [3, 0, 'from getters.get_piece_types import get_piece_types\n'],
            [4, 0, 'from misc.g_status_types import *\n'],
            [5, 0, 'from misc.JsonRecordError import JsonRecordError\n'],
            [6, 0, 'import json\n'],
            [7, 0, 'class JsonRecords(object):\n'],
            [8, 4, '    """contains info for new or saved game relevant to perfoming a castle or en_passant"""\n'],
            [9, 4, '    def __init__(self, file, board, j_records=None):\n'],
            [10, 8, '        if j_records is None:\n'],
            [11, 12, '            f = open(file, "r")\n'],
            [12, 12, '            json_data = f.read()\n'],
            [13, 12, '            records = json.loads(json_data)\n'],
            [14, 12, '            json.dumps(records, indent=4, sort_keys=False)\n'],
            [15, 12, '            f.close()\n'],
            [16, 0, '}\n'],
            [17, 8, '        else:\n'],
            [18, 12, '            records = j_records\n'],
            [19, 0, '}\n'],
            [20, 8, "        self.rooks_moved = records['rooks_moved']\n"],
            [21, 8, "        self.kings_moved = records['kings_moved']\n"],
            [22, 8, "        self.pawn_histories = records['pawn_histories']\n"],
            [23, 8, "        self.last_pawn_move = records['last_pawn_move']\n"],
            [24, 8, "        self.num_consecutive_non_pawn_moves = records['num_consecutive_non_pawn_moves']\n"],
            [25, 8, "        self.game_status = records['game_status']\n"],
            [26, 8, "        self.condition = records['condition']\n"],
            [27, 8, "        self.winner = records['winner']\n"],
            [28, 8, '        if j_records is None:\n'],
            [29, 12, '            self._init_pawn_ids(board, file=file)\n'],
            [30, 12, '            self._rankfile_to_tuple()\n'],
            [31, 0, '}\n'],
            [32, 8, '        else:\n'],
            [33, 12, '            self._rankfile_to_tuple(from_web=True)\n'],
            [34, 0, '}\n'],
            [35, 0, '}\n'],
            [36, 4, '    def _init_pawn_ids(self, board, file=""):\n'],
            [37, 8, '        """exchange the sqr that pawn started the game with, with the id for that pawn"""\n'],
            [38, 8, '        pawn_histories = {}\n'],
            [39, 8, '        for hist in self.pawn_histories.values():\n'],
            [40, 12, '            sqr1 = hist[-1]\n'],
            [41, 12, '            id_ = board[sqr1]\n'],
            [42, 12, '            pawn_histories[id_] = hist\n'],
            [43, 12, "            if get_piece_type(id_) != 'Pawn':\n"],
            [44, 16, '                print("ERROR: Pawn history not correct")\n'],
            [45, 16, '                print(file)\n'],
            [46, 16, '                print(sqr1)\n'],
            [47, 16, '                print(id_)\n'],
            [48, 16, '                raise JsonRecordError\n'],
            [49, 0, '}\n'],
            [50, 0, '}\n'],
            [51, 8, '        self.pawn_histories = pawn_histories\n'],
            [52, 0, '}\n'],
            [53, 4, '    def _init_pawn_locs(self):\n'],
            [54, 8,
             '        """swap the key of each pawn_history entry with the coordinate of its current location"""\n'],
            [55, 8, '        pawn_histories = {}\n'],
            [56, 8, '        for hist in self.pawn_histories.values():\n'],
            [57, 12, '            sqr = hist[-1]\n'],
            [58, 12, '            pawn_histories[sqr] = hist\n'],
            [59, 0, '}\n'],
            [60, 8, '        self.pawn_histories = pawn_histories\n'],
            [61, 0, '}\n'],
            [62, 4, '    def _rankfile_to_tuple(self, from_web=False):\n'],
            [63, 8, '        """convert the keys and ids for each type of record from a rankfile to a tuple"""\n'],
            [64, 8, '        rooks_moved = {}\n'],
            [65, 8, '        kings_moved = {}\n'],
            [66, 8, '        pawn_histories = {}\n'],
            [67, 8, '        last_pawn_move = None\n'],
            [68, 8, '        for rf in self.rooks_moved.keys():\n'],
            [69, 12, '            xy = to_xy(rf)\n'],
            [70, 12, '            rooks_moved[xy] = self.rooks_moved[rf]\n'],
            [71, 0, '}\n'],
            [72, 8, '        for rf in self.kings_moved.keys():\n'],
            [73, 12, '            xy = to_xy(rf)\n'],
            [74, 12, '            kings_moved[xy] = self.kings_moved[rf]\n'],
            [75, 0, '}\n'],
            [76, 8, '        if from_web:\n'],
            [77, 12, '            for id_ in self.pawn_histories.keys():\n'],
            [78, 16,
             '                self.pawn_histories[id_] = list(map(lambda li: to_xy(li), self.pawn_histories[id_]))\n'],
            [79, 0, '}\n'],
            [80, 0, '}\n'],
            [81, 8, '        else:\n'],
            [82, 12, '            for rf1 in self.pawn_histories.keys():\n'],
            [83, 16, '                xy1 = to_xy(rf1)\n'],
            [84, 16, '                pawn_histories[xy1] = []\n'],
            [85, 16, '                for rf2 in self.pawn_histories[rf1]:\n'],
            [86, 20, '                    xy2 = to_xy(rf2)\n'],
            [87, 20, '                    pawn_histories[xy1].append(xy2)\n'],
            [88, 0, '}\n'],
            [89, 0, '}\n'],
            [90, 0, '}\n'],
            [91, 8, '        self.rooks_moved = rooks_moved\n'],
            [92, 8, '        self.kings_moved = kings_moved\n'],
            [93, 8, '        self.pawn_histories = pawn_histories\n'],
            [94, 8, "        if self.last_pawn_move != 'None':\n"],
            [95, 12, '            self.last_pawn_move = to_xy(self.last_pawn_move)\n'],
            [96, 0, '}\n'],
            [97, 0, '}\n'],
            [98, 4, '    def _tuple_to_rankfile(self, for_web=False):\n'],
            [99, 8, '        """convert the keys and ids for each type of record from a tuple to a rankfile"""\n'],
            [100, 8, '        rooks_moved = {}\n'],
            [101, 8, '        kings_moved = {}\n'],
            [102, 8, '        pawn_histories = {}\n'],
            [103, 8, '        self._init_pawn_locs()\n'],
            [104, 8, '        for xy in self.rooks_moved.keys():\n'],
            [105, 12, '            rf = to_rankfile(xy)\n'],
            [106, 12, '            rooks_moved[rf] = self.rooks_moved[xy]\n'],
            [107, 0, '}\n'],
            [108, 8, '        for xy in self.kings_moved.keys():\n'],
            [109, 12, '            rf = to_rankfile(xy)\n'],
            [110, 12, '            kings_moved[rf] = self.kings_moved[xy]\n'],
            [111, 0, '}\n'],
            [112, 8, '        if for_web:\n'],
            [113, 12, '            for id_ in self.pawn_histories.keys():\n'],
            [114, 16,
             '                self.pawn_histories[id_] = list(map(lambda li: to_rankfile(li), self.pawn_histories[id_]))\n'],
            [115, 0, '}\n'],
            [116, 0, '}\n'],
            [117, 8, '        else:\n'],
            [118, 12, '            for xy1 in self.pawn_histories.keys():\n'],
            [119, 16, '                rf1 = to_rankfile(xy1)\n'],
            [120, 16, '                pawn_histories[rf1] = []\n'],
            [121, 16, '                for xy2 in self.pawn_histories[xy1]:\n'],
            [122, 20, '                    rf2 = to_rankfile(xy2)\n'],
            [123, 20, '                    pawn_histories[rf1].append(rf2)\n'],
            [124, 0, '}\n'],
            [125, 0, '}\n'],
            [126, 0, '}\n'],
            [127, 8, '        self.rooks_moved = rooks_moved\n'],
            [128, 8, '        self.kings_moved = kings_moved\n'],
            [129, 8, '        self.pawn_histories = pawn_histories\n'],
            [130, 8, "        if self.last_pawn_move != 'None':\n"],
            [131, 12, '            self.last_pawn_move = to_rankfile(self.last_pawn_move)\n'],
            [132, 0, '}\n'],
            [133, 0, '}\n'],
            [134, 4, '    def update_hist(self, id_, start, dest, promo_flag):\n'],
            [135, 8, '        """update json records depending on the piece type of id_ at location start"""\n'],
            [136, 8, '        p_type = get_piece_type(id_)\n'],
            [137, 8, '        if p_type != "Pawn":\n'],
            [138, 12, '            self.num_consecutive_non_pawn_moves += 1\n'],
            [139, 12, "            if p_type == 'Rook' and start in self.rooks_moved.keys():\n"],
            [140, 16, '                self.update_rooks_moved(start)\n'],
            [141, 0, '}\n'],
            [142, 12, "            elif p_type == 'King' and start in self.kings_moved.keys():\n"],
            [143, 16, '                self.update_kings_moved(start)\n'],
            [144, 0, '}\n'],
            [145, 0, '}\n'],
            [146, 8, '        else:\n'],
            [147, 12, '            self.reset_non_pawn_moves()\n'],
            [148, 12, '            self.last_pawn_move = dest\n'],
            [149, 12, '            self.update_pawn_history(id_, dest, promo_flag)\n'],
            [150, 0, '}\n'],
            [151, 8, '        return\n'],
            [152, 0, '}\n'],
            [153, 4, '    def update_state(self, board, ranges, enemy_color, npck):\n'],
            [154, 8, '        """\n'],
            [155, 9, '         update the status of the game: OVER or IN_PROGRESS\n'],
            [156, 9, "         update the winner of the game: 'w', 'b', or '-' (neither)\n"],
            [157, 9, "         udpate the condition of the enemy king: 'check', 'checkmate', 'stalemate', or 'safe'\n"],
            [158, 9, '         :param board: dict, game board\n'],
            [159, 9, '         :param npck: int, number of pieces checking the king\n'],
            [160, 9, '         :param ranges: dict, ranges of pieces of color\n'],
            [161, 9, '         :param enemy_color: str, color of king\n'],
            [162, 8, '        """\n'],
            [163, 8, '        if not any(ranges.values()):\n'],
            [164, 12, '            if npck > 0:\n'],
            [165, 16,
             "                self.condition, self.game_status, self.winner = 'checkmate', OVER, enemy_color\n"],
            [166, 0, '}\n'],
            [167, 12, '            else:\n'],
            [168, 16, "                self.condition, self.game_status, self.winner = 'stalemate', OVER, '-'\n"],
            [169, 0, '}\n'],
            [170, 12, '            return\n'],
            [171, 0, '}\n'],
            [172, 8, '        piece_types = get_piece_types(board)\n'],
            [173, 8,
             "        if piece_types in [['King', 'King'], ['Bishop', 'King', 'King'], ['King', 'King', 'Knight']]:\n"],
            [174, 12, "            self.condition, self.game_status, self.winner = 'stalemate', OVER, '-'\n"],
            [175, 0, '}\n'],
            [176, 8, '        elif npck > 0:\n'],
            [177, 12, "            self.condition, self.game_status, self.winner = 'check', IN_PROGRESS, '-'\n"],
            [178, 0, '}\n'],
            [179, 8, '        else:\n'],
            [180, 12, "            self.condition, self.game_status, self.winner = '', IN_PROGRESS, '-'\n"],
            [181, 0, '}\n'],
            [182, 0, '}\n'],
            [183, 4, '    def update_rooks_moved(self, sqr):\n'],
            [184, 8, '        """update rooks_moved because rook that start game at sqr has moved"""\n'],
            [185, 8, '        self.rooks_moved[sqr] = True\n'],
            [186, 0, '}\n'],
            [187, 4, '    def update_kings_moved(self, sqr):\n'],
            [188, 8, '        """update kings_moved because king that started game at sqr has moved"""\n'],
            [189, 8, '        self.kings_moved[sqr] = True\n'],
            [190, 0, '}\n'],
            [191, 4, '    def update_pawn_history(self, id_, new_loc, promo):\n'],
            [192, 8, '        """update location of pawn by appending its new location to its history"""\n'],
            [193, 8, '        if promo:\n'],
            [194, 12, '            del self.pawn_histories[id_]\n'],
            [195, 0, '}\n'],
            [196, 8, '        else:\n'],
            [197, 12, '            self.pawn_histories[id_].append(new_loc)\n'],
            [198, 0, '}\n'],
            [199, 0, '}\n'],
            [200, 4, '    def get_records(self, for_web=False):\n'],
            [201, 8, '        """return the json records as one python dict"""\n'],
            [202, 8, '        if for_web:\n'],
            [203, 12, '            self._tuple_to_rankfile(for_web=True)\n'],
            [204, 0, '}\n'],
            [205, 8, "        return {'rooks_moved': self.rooks_moved, 'kings_moved': self.kings_moved,\n"],
            [206, 16,
             "                'pawn_histories': self.pawn_histories, 'last_pawn_move': self.last_pawn_move,\n"],
            [207, 16, "                'num_consecutive_non_pawn_moves': self.num_consecutive_non_pawn_moves,\n"],
            [208, 16,
             "                'game_status': self.game_status, 'condition': self.condition, 'winner': self.winner}\n"],
            [209, 0, '}\n'],
            [210, 4, '    def reset_non_pawn_moves(self):\n'],
            [211, 8, '        """ a pawn has just moved, so reset number of consecutive non pawn moves to 0"""\n'],
            [212, 8, '        self.num_consecutive_non_pawn_moves = 0\n'],
            [213, 0, '}\n'],
            [214, 4, '    def delete_pawn(self, id):\n'],
            [215, 8, '        """delete pawn with id from pawn histories"""\n'],
            [216, 8, '        del self.pawn_histories[id]\n'],
            [217, 0, '}\n'],
            [218, 4, '    def has_king_moved(self, color):\n'],
            [219, 8, '        """return true/false of if the King of color has moved from its starting position"""\n'],
            [220, 8, "        if color == 'W':\n"],
            [221, 12, '            return self.kings_moved[(5, 1)]\n'],
            [222, 0, '}\n'],
            [223, 8, "        elif color == 'B':\n"],
            [224, 12, '            return self.kings_moved[(5, 8)]\n'],
            [225, 0, '}\n'],
            [226, 8, '        else:\n'],
            [227, 12, "            print('error: not a valid color\\n')\n"],
            [228, 12, '            return -1\n'],
            [229, 0, '}\n'],
            [230, 0, '}\n'],
            [231, 4, '    def get_start_king(self, color):\n'],
            [232, 8, '        """get starting position of king based off of color"""\n'],
            [233, 8, "        if color == 'W':\n"],
            [234, 12, '            return (5, 1)\n'],
            [235, 0, '}\n'],
            [236, 8, "        elif color == 'B':\n"],
            [237, 12, '            return (5, 8)\n'],
            [238, 0, '}\n'],
            [239, 8, '        else:\n'],
            [240, 12, "            print('error:invalid color')\n"],
            [241, 12, '            return -1\n'],
            [242, 0, '}\n'],
            [243, 0, '}\n'],
            [244, 4, '    def update_rook_dict(self, rooks_moved):\n'],
            [245, 8, '        """update rooks_moved dict to a new one"""\n'],
            [246, 8, '        self.rooks_moved = rooks_moved\n'],
            [247, 0, '}\n'],
            [248, 4, '    def queen_side_rook_moved(self, color):\n'],
            [249, 8,
             '        """return true if the queen side rook of the given color has moved, otherwise false"""\n'],
            [250, 8, "        if color == 'W':\n"],
            [251, 12, '            return self.rooks_moved[(1, 1)]\n'],
            [252, 0, '}\n'],
            [253, 8, "        elif color == 'B':\n"],
            [254, 12, '            return self.rooks_moved[(1, 8)]\n'],
            [255, 0, '}\n'],
            [256, 0, '}\n'],
            [257, 4, '    def king_side_rook_moved(self, color):\n'],
            [258, 8, '        """return true if the king side rook of the given color has moved, otherwise false"""\n'],
            [259, 8, "        if color == 'W':\n"],
            [260, 12, '            return self.rooks_moved[(8, 1)]\n'],
            [261, 0, '}\n'],
            [262, 8, "        elif color == 'B':\n"],
            [263, 12, '            return self.rooks_moved[(8, 8)]\n'],
            [264, 0, '}\n'],
            [265, 0, '}\n'],
            [266, 4, '    def __str__(self):\n'],
            [267, 8, '        """called when object is argument to print"""\n'],
            [268, 8, '        str_ = ""\n'],
            [269, 8, '        str_ += \'"rooks_moved": {\\n\'\n'],
            [270, 8, '        for k, v in self.rooks_moved.items():\n'],
            [271, 12, '            str_ += str(k)\n'],
            [272, 12, "            str_ += ':'\n"],
            [273, 12, '            str_ += str(v)\n'],
            [274, 12, "            str_ += '\\n'\n"],
            [275, 0, '}\n'],
            [276, 8, "        str_ += '},\\n'\n"],
            [277, 8, '        str_ += \'"kings_moved": {\\n\'\n'],
            [278, 8, '        for k, v in self.kings_moved.items():\n'],
            [279, 12, '            str_ += str(k)\n'],
            [280, 12, "            str_ += ':'\n"],
            [281, 12, '            str_ += str(v)\n'],
            [282, 12, "            str_ += '\\n'\n"],
            [283, 0, '}\n'],
            [284, 8, "        str_ += '},\\n'\n"],
            [285, 8, '        str_ += \'"pawn_histories": {\\n\'\n'],
            [286, 8, '        for k, v in self.pawn_histories.items():\n'],
            [287, 12, '            str_ += str(k)\n'],
            [288, 12, "            str_ += ':'\n"],
            [289, 12, '            str_ += str(v)\n'],
            [290, 12, "            str_ += '\\n'\n"],
            [291, 0, '}\n'],
            [292, 8, "        str_ += '},\\n'\n"],
            [293, 8, "        str_ += 'last_pawn_move'\n"],
            [294, 8, "        str_ += ':'\n"],
            [295, 8, '        str_ += str(self.last_pawn_move)\n'],
            [296, 8, "        str_ += ',\\n'\n"],
            [297, 8, "        str_ += 'num_consecutive_non_pawn_moves'\n"],
            [298, 8, "        str_ += ':'\n"],
            [299, 8, '        str_ += str(self.num_consecutive_non_pawn_moves)\n'],
            [300, 8, "        str_ += ',\\n'\n"],
            [301, 8, "        str_ += 'game_status'\n"],
            [302, 8, "        str_ += ':'\n"],
            [303, 8, '        str_ += str(self.game_status)\n'],
            [304, 8, "        str_ += ',\\n'\n"],
            [305, 8, "        str_ += 'winner'\n"],
            [306, 8, "        str_ += ':'\n"],
            [307, 8, '        str_ += str(self.winner)\n'],
            [308, 8, "        str_ += ',\\n'\n"],
            [309, 8, '        return str_\n'],
            [310, 0, '}\n'],
            [311, 0, '}\n'],
            [312, 0, 'if __name__ == "__main__":\n'],
            [313, 0, '}\n'],
            [314, 4, '    pass  # TODO: implement test\n']
        ]
    print_list(update_cb_indents(cflc_indexs_sorted_by_indent, cb_locations, line_data))